name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17' # 确保这里和 pom.xml 一致
          distribution: 'graalvm-community'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Environment
        run: |
          echo "GRAALVM_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Ensure mvnw is executable
        run: chmod +x mvnw

      - name: Build APK
        run: |
          # 强制指定 compiler.release 为 17 解决版本不支持问题
          ./mvnw gluonfx:build gluonfx:package \
            -Pandroid \
            -Dgluonfx.target=android \
            -DgraalvmHome=${{ env.JAVA_HOME }} \
            -Dmaven.compiler.release=17

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lark-apk
          path: target/gluonfx/aarch64-android/gvm/*.apk
